### ISSUE TITLE
Redirects for production site not all working

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1021]
If you include just http:// or nothing in front of the production URL, it still redirects to the main Parks website. For you @hectcastro ?

**Comment by hectcastro** [comment]
I haven't been able to reproduce this, but did notice this same issue shortly after we cut over because the previous endpoint redirected to the Parks website for non HTTPS. I think that this is a browser redirect caching issue.

Can you try from an incognito tab? That should avoid the browser redirect cache.

```bash
$ curl -I http://treescount.nycgovparks.org
HTTP/1.1 301 Moved Permanently
Content-Length: 184
Content-Type: text/html
Date: Wed, 01 Apr 2015 13:39:51 GMT
Location: https://treescount.nycgovparks.org/
Server: nginx/1.6.2
Connection: keep-alive
```

The gibberish above just illustrates that a request via HTTP is redirected to HTTPS (via the `Location` header).

**Comment by dboyer** [comment]
I was able to reach the site when in an incognito tab. I did several hard refreshes and new browser windows in Firefox before I entered the issue and it still happens.

**Comment by jwalgran** [comment]
I visited the site with an http:// protocol in Firefox, Chrome, and Safari on desktop, and Mobile Safari on iOS and got proper redirects.

**Comment by dboyer** [comment]
I'm closing this since there is no immediate option for getting rid of the cache issues in Firefox and it's unlikely to impact more than a handful of people.
