### ISSUE TITLE
Button to download printable map spins but never stops loading

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1087]
On staging

**Comment by jwalgran** [comment]
I saw this behavior in the case where I had an event created before we added the PDF feature. Because the PDF is only created when an event is created or the location of an event is changed, old, test events do not have PDFs. This will not be a problem in production since the PDF feature will be in place for all created events.

If there is an infinite spinner on a brand new event, that is something we will need to dig into.

**Comment by dboyer** [comment]
You are correct. I had no issues downloading the PDF for a new event. Closing this.
