### ISSUE TITLE
In My Trees tab, clicking events circle should show events you attended

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1103]

**Comment by RickMohr** [comment]
I believe the number of events is correct. The problem we saw in RRP was that it links to the general events page rather than showing the events you attended. If we want to show the events you attended it should probably be in a modal on the same page, with links to the actual events.

@dboyer, I've edited the title. Should we still do this?

**Comment by kdeloach** [comment]
I'm adding a blocked label until we know for sure if we should do this or not.

**Comment by dboyer** [comment]
Let's wait on this. I think it's an enhancement rather than a necessity.
