### ISSUE TITLE
Reservations page "Start Mapping" button disappears

### ISSUE THREAD

**Issue by kdeloach** [azavea/nyc-trees#1227]
I noticed that when the Reservations page first loads there's a nice big "Start Mapping" button, but once you select any blockfaces, it disappears.

1. Initial page load
![image](https://cloud.githubusercontent.com/assets/43062/7195814/3e90c34a-e494-11e4-8583-c4692ca34ce9.png)

2. Select random blockface
![image](https://cloud.githubusercontent.com/assets/43062/7195817/4aa3aec2-e494-11e4-8aaa-b221d3da6344.png)

3. Deselect blockface, where'd "Start Mapping" go?
![image](https://cloud.githubusercontent.com/assets/43062/7195825/65930660-e494-11e4-83f2-1b195260d263.png)

This also affects the Desktop version.

**Comment by jfrankl** [comment]
@kdeloach This is intentional, though maybe not the correct approach. Here's the issue:

**Start Mapping** is really a secondary on this page. People can access the **Start Mapping** section through the main navigation (or at least they will after the latest round of feedback goes through). This page is focused on setting reservations.

Part of why this is confusing is the distinction between **Start Mapping** and **Finish Reservation**. Once someone adds or removes a blockface, they need to click **Finish Reservation** to confirm changes. If they were to click **Start Mapping** and it retained its standard functionality, they would lose their changes, which is confusing in its own way.

Here are a couple of ways we can adjust this, curious what you think @dboyer:

1. We could remove **Start Mapping** from this page and let people find it in the main navigation—focus this page on the reservation process; we could add a line in the overlay help text on this page that says "Want to map blocks you've already reserved? Click **Start Mapping** in the main navigation." 
2. We could change the name of this page to *Make Reservations* or *Reserve Blocks* to distinguish it from mapping reservations
3. We could allow users to jump back to the **Start Mapping** or **Add/Remove Blocks** buttons that they currently see when they land on the page, *but* if they they click on **Start Mapping** they will lose any new blocks they added or removed
4. We could allow users to jump back to the **Start Mapping** or **Add/Remove Blocks** buttons that they currently see when they land on the page *and* if they they click on **Start Mapping** they will lose any new blocks they added or removed 

Given that we are going to display **Start Mapping** in the main navigation at all times, I think we should go with numbers 1 and 2 above, but I am open to other ideas. Will bring this up with the design team today.

![image](https://cloud.githubusercontent.com/assets/1809908/7229967/74e11418-e737-11e4-909f-1f97f9122a34.png)

**Comment by jfrankl** [comment]
Talked with Deb. We are going to remove the **Start Mapping** button section. All mapping with start through the **Treecorder** link that will always be visible in the main navigation.

**Comment by RickMohr** [comment]
We'll keep the "Start Mapping" button on the checkout confirmation page and the event arrival page, right?

**Comment by jfrankl** [comment]
Definitely yes.

**Comment by jfrankl** [comment]
Closing this issue, replaced by #1309.
