### ISSUE TITLE
cannot search for user on old safari

### ISSUE THREAD

**Issue by lliss** [azavea/nyc-trees#1237]
![user_issue](https://cloud.githubusercontent.com/assets/903219/7209010/a412c91a-e512-11e4-9f16-845edd6c4f37.jpg)

**Comment by jfrankl** [comment]
Maybe an issue with using ```transform: translate```?

**Comment by lliss** [comment]
Notice that it does this weird thing where it opens a search bar on the page after clicking the username field. It doesn't show options there or allow me to type.

**Comment by designmatty** [comment]
@lliss Do you know which version of iOS this was?

**Comment by lliss** [comment]
4.2.1

**Comment by lliss** [comment]
I have the device with me if you want to try it @designmatty

**Comment by designmatty** [comment]
Yeah if you don't mind @lliss. That would be really helpful, thanks.

**Comment by designmatty** [comment]
@jfrankl this seems to have been fixed at some point however now there's a new issue on old iOS roughly 4.3.2 and down. On the treecorder section of the survey you can no longer scroll. I'll be opening an new issue and tackling the problem there. As for this one, I'm going to close this issue since it seems to be working.
