### ISSUE TITLE
Reservations page: Overlapping text in action bar

### ISSUE THREAD

**Issue by RickMohr** [azavea/nyc-trees#1243]
1. Panels overlap
2. Chevron overlaps number

![img_3276](https://cloud.githubusercontent.com/assets/2162993/7210384/4573fc64-e51f-11e4-8d55-4a2020e30528.PNG)

**Comment by jfrankl** [comment]
I think this was fixed by #1232. Will confirm.

**Comment by jfrankl** [comment]
Fixed by #1232. Looking fine (at least in terms of this issue) on iOS 6 and Android 4.2.

![image](https://cloud.githubusercontent.com/assets/1809908/7222077/6baff36e-e6d3-11e4-9bb7-42f3b319a8b3.png)

![image](https://cloud.githubusercontent.com/assets/1809908/7222087/c46d5bea-e6d3-11e4-9fd6-31f325d94646.png)
