### ISSUE TITLE
Add Treecorder link in main navigation

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1252]
Split off from #1228 

Could the Treecorder be added as an additional link in the Navigation bar, as a single point of entry to mapping functions (rather than through reservations / events)?

@jfrankl Would you see this replacing the Start Mapping button?

**Comment by jfrankl** [comment]
@dboyer I do think this would replace **Start Mapping**. Once a developer adds this in, I can style it to make it stand out from the rest of the navigation.

**Comment by dboyer** [comment]
@jfrankl  What do you think about having the Treecorder link always be there? If you didn't have any reservations or event rsvps, it would just show a page saying "You have nothing to map...."

I feel like some of the confusion among users is because sometimes the Start Mapping link is there and sometimes it's not.

**Comment by dboyer** [comment]
The Treecorder link will replace start mapping in the navigation and will permanently be displayed. It shouldn't be conditional.

**Comment by RickMohr** [comment]
What should happen when you click it? Proposal:
* If you are RSVPd to a current event, same as when you "start mapping" from that event's arrival page
* Otherwise, if you have reservations, same as when you "start mapping" from the reservations page
* Otherwise, show the reservations page (which will redirect if you haven't finished training)

**Comment by jfrankl** [comment]
+1 on that plan Rick.

On Tue, Apr 21, 2015 at 10:27 AM, Rick Mohr <notifications@github.com>
wrote:

> What should happen when you click it? Proposal:
>
>    - If you are RSVPd to a current event, same as when you "start
>    mapping" from that event's arrival page
>    - Otherwise, if you have reservations, same as when you "start
>    mapping" from the reservations page
>    - Otherwise, show the reservations page (which will redirect if you
>    haven't finished training)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1252#issuecomment-94813795>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by dboyer** [comment]
Two other scenarios:

- If you are not logged in or haven't completed online training, send to the training instructions page since you need to complete additional steps before you can use the Treecorder.
- If you aren't an individual mapper, redirect to the events page? Maybe not?

**Comment by RickMohr** [comment]
@dboyer, if you are not logged in I think it should take you to the login page, and then (once you log in) to the appropriate page as above.

**Comment by RickMohr** [comment]
OK, here's the whole enchilada:
* If user isn't logged in:
  * Show login page
  * Once logged in, show appropriate page as below
* If user hasn't completed online training, show training instructions page
* If RSVPd to a current event:
  * If not checked in, show event arrival page
  * Otherwise show Treecorder start page for the event
* If user is not an individual mapper, show reservations instructions page
* Otherwise, show Treecorder start page for individual mappers

**Comment by jwalgran** [comment]
Simple ;-)

**Comment by dboyer** [comment]
What could possibly be confusing about that???

That sounds good to me. Thanks for working through the details.
