### ISSUE TITLE
Group borders are reported as uploaded, but do not appear on the map

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1407]
Parks did an geojson upload to staging and got statuses like this

![screen shot 2015-04-22 at 8 27 43 pm](https://cloud.githubusercontent.com/assets/17363/7290083/258d0f36-e92e-11e4-9173-3e1c724e8232.png)

Indicating that some boundaries were uploaded, but when they browsed the group progress page the polygons were not there (only 2 manually created test ones were)

![screen shot 2015-04-22 at 8 29 33 pm](https://cloud.githubusercontent.com/assets/17363/7290095/4f360126-e92e-11e4-889b-ee1dc5d96308.png)

**Comment by RickMohr** [comment]
We only display group polygons if they have territory assigned. Because none of the uploaded groups had territory, none of them were displayed. I added territory for the group "American Littoral Society - NE Chapter", and now its polygon shows up too:

![image](https://cloud.githubusercontent.com/assets/2162993/7298480/ee93a9d4-e99d-11e4-8ad6-8f2188b4fc93.png)

**Comment by RickMohr** [comment]
@dboyer says we should show all polygons regardless of whether their group has territory.

**Comment by jwalgran** [comment]
![screen shot 2015-04-23 at 8 34 41 am](https://cloud.githubusercontent.com/assets/17363/7300838/9dcd30e2-e993-11e4-888f-1d95af1d7c84.png)
