### ISSUE TITLE
No error validation messages shown on iPhones

### ISSUE THREAD

**Issue by maurizi** [azavea/nyc-trees#1664]
Steps to reproduce:
1. Go to the treecorder.
2. Leave a field unchecked
3. Go to the bottom and choose "Add another Tree"

Expected: It focuses on the first field with an error and displays a bubble with a validation message
Actual: It focuses on the first incorrect field, but there is no validation message.

Error validations do appear for me on Firefox (Android and desktop), but not on iOS (iPhone 4 on iOS7 and iPhone 4S on iOS 8).

Do some research into existing solutions for showing custom validation messages.

**Comment by jwalgran** [comment]
iOS does not show form validation messages according to http://caniuse.com/#feat=form-validation

![can-i-use](https://cloud.githubusercontent.com/assets/17363/7642201/16f40926-fa44-11e4-9b1e-bb86deed7355.png)

**Comment by maurizi** [comment]
We do still get error *checking*, so users won't be submitting invalid data, like negative numbers.

However, not knowing why clicking "Submit" made the screen focus on a field is not very good UX.
We could show validation messages ourselves for iOS devices, instead of relying on the browser to do so.

**Comment by dboyer** [comment]
@jfrankl What are your thoughts on this from a UX perspective?

**Comment by jfrankl** [comment]
It would definitely be preferable to have validate messages. Otherwise, it
just looks like you accidentally scrolled up on the page. I'm more
concerned about someone not knowing that the form didn't validate than
knowing why it didn't validate (though I'm concerned about both). Right now
it's not clear that you need to make a change.

On Wed, May 20, 2015 at 4:38 PM, dboyer <notifications@github.com> wrote:

> @jfrankl <https://github.com/jfrankl> What are your thoughts on this from
> a UX perspective?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1664#issuecomment-104030780>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
