### ISSUE TITLE
Allow a survey to be restarted from the preview map

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#1858]
If you, for example, start mapping on the wrong side of the street, we should allow the mapper to start over.

**Comment by dboyer** [comment]
Since this is going back to the block selection page, can we change the button from "Restart Block" to "Wrong Block Selected - Start Over." Or something else shorter.

**Comment by maurizi** [comment]
People are not necessarily restarting because they selected the wrong block
edge - they may have picked the right block but got the right/left side
wrong.

Perhaps we could just say "Restart"?

On Wed, Apr 27, 2016, 11:14 dboyer <notifications@github.com> wrote:

> Since this is going back to the block selection page, can we change the
> button from "Restart Block" to "Wrong Block Selected - Start Over." Or
> something else shorter.
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/1858#issuecomment-215115833>
>
-- 

Michael Maurizi, Software Developer
Azavea |  990 Spring Garden, 5th Floor, Philadelphia, PA
mmaurizi@azavea.com <rcr@azavea.com> | Web azavea.com
<http://www.azavea.com/>  |  @azavea <http://twitter.com/azavea>

**Comment by dboyer** [comment]
Let's go with Restart.
