### ISSUE TITLE
Preview screen layout incorrect on tablet

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#1865]
Testing on iPad using Safari browser:

1. Enter Treecorder and map first tree with tablet in vertical orientation
2. Click preview button. Close preview/restart options appear above the map (see screenshot)
3. Click "close block preview" and return to Treecorder. Page does not display correctly (see screenshot)

This issue resolves if you switch to a horizontal alignment for the iPad.

**Comment by dboyer** [comment]
![image](https://cloud.githubusercontent.com/assets/516764/15028345/739c07c4-1216-11e6-8d2b-89b8173ba362.jpg)
![image](https://cloud.githubusercontent.com/assets/516764/15028346/739e78e2-1216-11e6-8732-b09365dbe2ae.jpg)

**Comment by dboyer** [comment]
![treecorder_preview](https://cloud.githubusercontent.com/assets/516764/15028468/123a6e52-1217-11e6-911f-2cd5a1b19c1b.jpg)
![treecorder_preview2](https://cloud.githubusercontent.com/assets/516764/15028469/123ab68c-1217-11e6-952b-05d7e2439003.jpg)

**Comment by dboyer** [comment]
This may be for @designmatty

**Comment by jwalgran** [comment]
I was not able to reproduce this on a 1st generation iPad mini running iOS 9.2 or the Xcode iOS simulator set to iPad 2 iOS 9.3.

@dboyer is this something that you can reliably reproduce? What type of iPad is it and what version of iOS is it running?

**Comment by dboyer** [comment]
I can reliably reproduce it on an old iPad 2 running iOS 7.1.1. Parks is reporting similar issues with the preview screen loading in the upper left corner of the page on iPads and Galaxy tablets. I've asked for screenshots.

**Comment by designmatty** [comment]
So I was able to reproduce it in browserstack. I understand the issue and I think I found a solution but have not yet implemented it. The issue is that when you open the keyboard on focus of an input and then unfocus/hide the keyboard any fixed element scrolls down on the page equal to that of the keyboard.

The hacky fix is here: http://stackoverflow.com/questions/15273098/how-do-i-stop-my-fixed-navigation-from-moving-like-this-when-the-virtual-keyboar

**Comment by designmatty** [comment]
so `.map-survey` and `.main-header` will need the fix implemented to them.

**Comment by designmatty** [comment]
@jwalgran i recommend logging into our browserstack.com account and running some tests. After a lot of testing I think this is the best we will get. 

The fix makes the map and navbar position absolute instead of fixed. The only bug, which I've concluded is an ios 7 bug, is the browser makes the height of the app a bit taller than 100% and cuts like 10px off the top of the navbar. The user can scroll the page to bring it back into view, but all buttons are still accessible regardless. 

I went as far as deleting every element from the page to figure out the source of the extra height. After literally removing everything but the `html, head, body` the problem persisted. Even all styles were removed. Definitely is io7 bug.

**Comment by designmatty** [comment]
![screen shot 2016-05-05 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/1928955/15050753/8a5ac920-12c3-11e6-8e3f-cac4c05bd4fa.png)

**Comment by dboyer** [comment]
I'm less concerned if it's just an iOS 7 bug although we should implement a fix if one is available. I initially thought https://github.com/azavea/nyc-trees/issues/1867 was connected to this issue so wanted to dig into it. IT looks like that might be something else though.
