### ISSUE TITLE
Some options don't work on event drop-down on groups page

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#408]
Testing on staging. 
![event_dropdown](https://cloud.githubusercontent.com/assets/516764/5977077/8e0c39fe-a862-11e4-9c2c-7856ef06ae21.png)

At 9:20, I set up an event to run from 9:10-10:10. Since it was in progress, I assumed I could use the drop-down arrow for that event on my groups page to email attendees, RSVP, and check-in for the event. See screenshot.

First issue is that the event was put in Past even though it was still occurring. Seems like events shouldn't move to the past tab until after the end time for the event is past.

Second issue is that nothing happened when I clicked RSVP, email attendees (perhaps because email isn't set up on staging), or event check-in. It seems like I should at least be taken to the event check-in page when I click that option.

**Comment by RickMohr** [comment]
`Edit Details`, `Email Attendees`, and `Event Check-in` are just links to already existing pages.

`RSVP to Event` should probably function in a similar fashion to the RSVP button for normal users, where it toggles between RSVP, and un-RSVP.

@dboyer, what does `Get Shareable Link` do, copy the event detail URL to the clipboard, and show an alert with the URL?

**Comment by dboyer** [comment]
If an event is marked as private, users can only register via a unique URL for that event. Get Shareable Link lets the group admin get that URL to email to people. If the event isn't private, I see the Get Shareable Link just being a link to the event page.

**Comment by RickMohr** [comment]
@dboyer, I think it would be simpler for us and clearer for group admins if we:
* Remove the "RSVP to Event" link on this page
* Show the "RSVP" button on the event detail page when a group admin is viewing it

Currently when a group admin is viewing the event detail page we show the "Admin" button instead of the "RSVP" button. I'm proposing that we show both buttons.

Otherwise it's difficult for a group admin to tell whether they have registered for one of their group's events. The only way they could tell is to go to the "Events" tab of their group's management page, click on the drop-down, and see if the link is "RSVP" or "un-RSVP". Not very intuitive. With my proposal they can tell by looking at the event's detail page just like they would for another group's event.

**Comment by dboyer** [comment]
@RickMohr I'm fine with that approach.
