### ISSUE TITLE
Training shouldn't show "Try Again" and "Previous" buttons

### ISSUE THREAD

**Issue by jfrankl** [azavea/nyc-trees#572]
The training button area should either show:

- Previous and Next
- Previous
- Next
- Try Again

In situations where it shows Try Again and Previous, I think it should just show Try Again.

This is an example of where this is happening:

![image](https://cloud.githubusercontent.com/assets/1809908/6219028/bedc008a-b5f2-11e4-801e-91aa3adc95a2.png)

**Comment by steventlamb** [comment]
Agreed.

**Comment by steventlamb** [comment]
@jfrankl in a similar vein, I think it's weird that you can go '<- Back' after successfully completing a question, because it's an ambiguous state change: are you going back to the question or the page before?
![screenshot from 2015-02-16 16 35 33](https://cloud.githubusercontent.com/assets/1699455/6219610/f5010e7e-b5f9-11e4-8181-bcbc5bfce596.png)

Do you think we should hide the `<- Back` button on success too?

**Comment by jfrankl** [comment]
Yeah, let's hide it.

On Mon, Feb 16, 2015 at 4:38 PM, Steve Lamb <notifications@github.com>
wrote:

> @jfrankl <https://github.com/jfrankl> in a similar vein, I think it's
> weird that you can go '<- Back' after successfully completing a question,
> because it's an ambiguous state change: are you going back to the question
> or the page before?
> [image: screenshot from 2015-02-16 16 35 33]
> <https://cloud.githubusercontent.com/assets/1699455/6219610/f5010e7e-b5f9-11e4-8181-bcbc5bfce596.png>
>
> Do you think we should hide the <- Back button on success too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/nyc-trees/issues/572#issuecomment-74576291>.
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>
