### ISSUE TITLE
Training page for anonymous users should show some text and link to PDF training materials

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#589]
We are restricting the interactive training materials to registered users, but Parks will is developing a PDF version of the training that we will need to make available to the unregistered public.

**Comment by kdeloach** [comment]
What text should we display for anonymous users? Is there another version of the training materials PDF?

**Comment by dboyer** [comment]
Let me work on getting text for this. It sounds like we have some gaps in the training material text.

**Comment by dboyer** [comment]
This text should appear for both anonymous users and those who have created an account but not started training. 

Text underneath Training header (on left side of screen when on desktop):
Can we count on you? Get started on your training today and help us make trees count!

Header text (top of right column when on desktop):
Become a trained volun<b>treer</b> today!

Body text before Getting Started section:
Click Start to begin your volun<b>treer</b> training. Once you complete all sections, you can sign up for an event to use what you've learned to map trees!

You can also download a PDF of the training materials here.  (here is a hyperlink to training PDF - that manual is saved at \data\Training_Materials but may change in the next day)

**Comment by steventlamb** [comment]
@dboyer I have some questions.

* It doesn't look like all this text applies for both anonymous users and those who haven't yet started. For example, 'Click Start...' won't always be there if they aren't logged in.

* do we always include the PDF for all 4 cases? (not logged in, not started, not finished, complete).

* What text should go in the header for not logged in and not started? If we use the "Become a trained voluntreer today!", we can't apply bolding of 'treer', because everything is bold.
![screenshot from 2015-04-16 16 24 20](https://cloud.githubusercontent.com/assets/1699455/7190561/18124dea-e455-11e4-8b07-0944f09f4f7a.png)

**Comment by maurizi** [comment]
@steventlamb We've been wrapping `treer` in header tags inside of `<span class="color--primary"></span>` to make the `treer` green.

**Comment by dboyer** [comment]
@steventlamb 

1. Why won't the Start button be there if the user isn't logged in? I thought we were prompting for login when the user tried to go to the Getting Started page. Has that changed?

2. Yes, the PDF should always be visible to everyone from the training page.

3. Become a trained voluntreer is fine for the heading. The lack of bolding on treer isn't an issue since it's all bold.
