### ISSUE TITLE
Add in crosshairs for selecting blockface to map

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#884]
The original TreeKIT app included crosshairs that the user placed over the blockface they wished to map. TreeKIT did extensive user testing and found the crosshairs cut down on incorrect block selection as part of mapping. http://treekit.github.io/treekit/#startlocation

**Comment by jfrankl** [comment]
Sounds good. We'll need a developer to implement this.

**Comment by jwalgran** [comment]
Rick built the beginnings of it into the event edit page, where you choose the location. We just need a bit more code to do feature selection as the map moves under the crosshairs.

**Comment by RickMohr** [comment]
We select blocks in other places besides the treecorder, and accuracy of block selection was also raised in user testing. Do we want to use crosshairs elsewhere, or just in the treecorder? The "New Reservations" page comes to mind, and the "My Reservations" page (if it stays as a map.) Not the progress page (since block selection is secondary there) or the admin territory page.

**Comment by kdeloach** [comment]
This card just applies to the Treecorder. Progress & reservations are a separate issue.

**Comment by dboyer** [comment]
Correct, limit crosshairs to the Treecorder. No need to implement elsewhere for now.
