### ISSUE TITLE
Soft launch - April 1

### ISSUE THREAD

**Issue by dboyer** [azavea/nyc-trees#961]
On April 1, production needs to be live in soft launch mode. Users need to be able to register for an account and go to their user profile. 

This is a “bucket” issue to cover supporting everything we will need to iron out for deployment.

### Deployment Tasks and Decisions

- [x] Instance Types
- [x] DB Size __20 GB__
- [x] Breaking changes after domain switch
- [x] __slamb__ Failover Site
- [x] Pingdom Setup
- [x] SNS Setup (SMS)
- [x] Self-Hosted Font

### Application Bugs
- [x] __jwalgran__ Hide progress counts on anonymous and logged in home page
- [x] __slamb__ Remove "show me the map" link in top image
- [x] __jwalgran__ Link contact as a mailto link to treescount.help@parks.nyc.gov and hide privacy in sidebar navigation 
- [x] __slamb__ Update copyright info to 2015
- [x] __maurizi__ Update home page text
- [x] __maurizi__ Update About & FAQ text
- [x] __jwalgran__ Replace hero image 
- ~~Add sponsor logos~~

**Comment by hectcastro** [comment]
Regarding instance types, application and tile servers are set to `m3.medium`. If that becomes an issue down the road, we can scale them up to `m3.large` or out to more `m3.mediums`.

The RDS database server is an `db.m3.large`, and the ElastiCache instance is `cache.m1.small`. We can scale both of them up if needed. Starting the cache at `m1.small` because that is the smallest instance type with backup capabilities.

The monitoring server is the same as staging with a `t2.medium`. The NAT instances are `t2.mediums` as well based on Jeremy's [recommendations](http://www.azavea.com/blogs/labs/2015/01/selecting-a-nat-instance-size-on-ec2/).
