### ISSUE TITLE
Admin UI to add/edit Group polygon

### ISSUE THREAD

**Issue by jwalgran** [azavea/nyc-trees#975]
Probably incorporated into the territory editor

**Comment by RickMohr** [comment]
Could you please add a bit of detail? Was this a customer request?

**Comment by jwalgran** [comment]
It will be best for @dboyer to fill in on Monday. As I understand it there is a strong desire to show the territory of all the groups together on one map of polygons. See also https://github.com/azavea/nyc-trees/issues/970

**Comment by dboyer** [comment]
Parks has a shapefile with polygons outlining the group areas. While we can upload those polygons, I don't think we necessarily to support editing them since that is outside of scope. I'm also concerned about confusion with census admins editing polygons and not the block faces assigned to the group and the two areas not matching. I'm talking with Parks about this so let's hold off on anything related to polygons for a couple more days.

**Comment by RickMohr** [comment]
We will probably skip this in favor of #1134
